### ISSUE TITLE
Query optimizer doesn't like the new Diseases VL.

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#124]
The query optimizer is throwing errors when trying to optimize the new Diseases VL:

```
/ajax/viewlist.php?viewlistid=Diseases&object=Disease&id=0&order=symbol%2CASC&options=true&search_tissues=bones&page_size=100&page=1 returned error in code block QueryOptimizer.
Query : SELECT COUNT(*) FROM lovd_v3_diseases AS d WHERE d.id > 0 HAVING (tissues LIKE ?)
Error : Error in getRowCountForViewList() while executing optimized query.
```

**Comment by mkroon1** [comment]
If I remember correctly, this will fall back to the 'old and slow' method, right? Meaning that this is not a high priority issue.

**Comment by ifokkema** [comment]
Correct, nothing fails since we have a fallback, but since the query looks fine by me, and it's the first query to fail, it's probably a very quick fix :wink:
