### ISSUE TITLE
Make LOVD compatible with the `ONLY_FULL_GROUP_BY` MySQL setting.

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#144]
LOVD is currently not compatible with the `ONLY_FULL_GROUP_BY` MySQL setting.

From the MySQL manual:
> In MySQL 5.7.5, the ONLY_FULL_GROUP_BY SQL mode is enabled by default because GROUP BY processing has become more sophisticated to include detection of functional dependencies. However, if you find that having ONLY_FULL_GROUP_BY enabled causes queries for existing applications to be rejected, either of these actions should restore operation:
> 
> If it is possible to modify an offending query, do so, either so that nonaggregated columns are functionally dependent on GROUP BY columns, or by referring to nonaggregated columns using ANY_VALUE().

**Comment by mkroon1** [comment]
Accounting for problems described in the MySQL manual for [handling group by queries](http://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html), and also avoiding the use of `ANY_VALUE()` which was only introduced in MySQL recently, I'm planning the following steps:

Fix all queries with non-unique identifying GROUP BY fields and non-aggregated fields in the SELECT, HAVING or ORDER BY clause. Use `MAX()` for position fields and `MIN()` for other fields.

Fix all queries with SELECT DISTINCT and ORDER BY clause where fields in the ORDER BY clause do not refer selected fields or are not aggregates.
