### ISSUE TITLE
LOVD uses old-style constructors.

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#156]
As of PHP 7, constructors defined as methods with the same name as the class are [deprecated](http://php.net/manual/en/language.oop5.decon.php). LOVD currently outputs notices like the one below.

> **Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ProgressBar has a deprecated constructor in /src/class/progress_bar.php on line 41**

**Comment by ifokkema** [comment]
Fixed in fe06dbb.
