### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sptaylor** [LOVDnl/LOVD3#157]
/variants/DMD/unique?search_var_status=%3D%22Marked%22%7C%3D%22Public%22 returned error in code block Custom_ViewList::viewList().
Query : SELECT CONCAT(vog.id, IFNULL(CONCAT(":", vot.transcriptid), "")) AS row_id, vot.id AS votid, vot.transcriptid, vot.position_c_start, vot.position_c_start_intron, vot.position_c_end, vot.position_c_end_intronTRIM(BOTH "?" FROM TRIM(LEADING "c." FROM REPLACE(REPLACE(`VariantOnTranscript/DNA`, ")", ""), "(", ""))) AS vot_clean_dna_change, COUNT(`VariantOnTranscript/DNA`) AS vot_reported, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnTranscript/DNA`, "") SEPARATOR ";;") AS `VariantOnTranscript/DNA`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnTranscript/RNA`, "") SEPARATOR ";;") AS `VariantOnTranscript/RNA`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnTranscript/Protein`, "") SEPARATOR ";;") AS `VariantOnTranscript/Protein`, vog.id AS vogid, vog.chromosome, `VariantOnGenome/DNA`, `VariantOnGenome/Reference`, `VariantOnGenome/DBID`, `VariantOnGenome/Frequency`, `VariantOnGenome/Frequency/EA`, `VariantOnGenome/Frequency/AA`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/DNA`, "") SEPARATOR ";;") AS `VariantOnGenome/DNA`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/Reference`, "") SEPARATOR ";;") AS `VariantOnGenome/Reference`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/DBID`, "") SEPARATOR ";;") AS `VariantOnGenome/DBID`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/Frequency`, "") SEPARATOR ";;") AS `VariantOnGenome/Frequency`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/Frequency/EA`, "") SEPARATOR ";;") AS `VariantOnGenome/Frequency/EA`, GROUP_CONCAT(DISTINCT NULLIF(`VariantOnGenome/Frequency/AA`, "") SEPARATOR ";;") AS `VariantOnGenome/Frequency/AA` FROM lovd_variants_on_transcripts AS vot LEFT JOIN lovd_variants AS vog ON (vot.id = vog.id) WHERE (vot.transcriptid = ?) GROUP BY `position_c_start`, `position_c_start_intron`, `position_c_end`, `position_c_end_intron`, vot_clean_dna_change ORDER BY position_c_start ASC, position_c_start_intron ASC, position_c_end ASC, position_c_end_intron ASC, `VariantOnTranscript/DNA` ASC LIMIT 100 OFFSET 0
Error : Error in PDOStatement::execute() while executing prepared query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BOTH "?" FROM TRIM(LEADING "c." FROM REPLACE(REPLACE(`VariantOnTranscript/DNA`, ' at line 1

**Comment by ifokkema** [comment]
Hi there! Thanks for the bug report. Could you tell us what the URL was of the page that had this error, and any possible search terms you used that triggered this?

**Comment by sptaylor** [comment]
Here is the URL: http://databases.lovd.nl/whole_genome/variants/DMD/unique?search_var_status=%3D%22Marked%22%7C%3D%22Public%22 <http://databases.lovd.nl/whole_genome/variants/DMD/unique?search_var_status==%22Marked%22|=%22Public%22>

I got there by navigating to the LOVD whole genome DMD page (http://databases.lovd.nl/whole_genome/genes/DMD <http://databases.lovd.nl/whole_genome/genes/DMD>) and clicking on the hyperlink displaying “675” next to “unique public DNA variants reported”.

Best,

Paige

**Comment by ifokkema** [comment]
Excellent, thank you. We have manually made some modifications in that installation, and the unique variant view is quite useless there as none of the variants have more than one observation. We must have made a mistake in editing that installation. We'll look into it!

**Comment by ifokkema** [comment]
Fixed just now; caused by an error when modifying the `whole genome' installation specifically. Thanks for your report!
