### ISSUE TITLE
Let test installations identify themselves correctly

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#174]
Properly showing LOVD installation counts has become completely impossible due to extremely high numbers. The busiest month, September 2016, reported as many as 4000 LOVD3 installations. Apparently test installations aren't identified (anymore?) as such.
Test installations on Travis should be marked as such. There is code in place for it, but apparently that doesn't work anymore.
Test installations ran locally should also be marked as such, so that installation/deinstallation rounds don't pollute the statistics.

**Comment by mkroon1** [comment]
As far as I know, identification is done with the installation's signature. Which for test installations is (or should be) overwritten by [these lines](https://github.com/LOVDnl/LOVD3/blob/master/src/install/index.php#L337-L344).

A general fix would be to allow setting the signature in the `config.ini.php` file. That way, developer names don't have to be mentioned explicitly in the code.

**Comment by ifokkema** [comment]
> A general fix would be to allow setting the signature in the `config.ini.php` file. That way, developer names don't have to be mentioned explicitly in the code.

No, we should prevent others from messing with that ID as much as possible. Clashes in this ID will bring immense issues with them. Changes in this ID while the LOVD is live will be even worse. If the automatically generated ID needs to be overridden, this needs to be done in the code. It's actually probably a quick fix, we'll just need to find an environment variable that we can use, if `$_SERVER['USER']` is no longer appropriate.
