### ISSUE TITLE
Download link missing from gene homepage for public, even if setting is enabled

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#175]
The download link for the public, allowing a non-authorized user to download the full gene data (individuals, phenotypes, screenings, variants), is missing from the gene homepage, even if the curator has enabled this option.
When the curator enabled this option, the download link should be available and the download should contain all public data from this gene. Non-public columns should be removed.

**Comment by ifokkema** [comment]
Duplicate of #78.

**Comment by mkroon1** [comment]
Most of export functionality already exists in `download.php`. On the gene homepage we can link to `/download/all/gene/NAME`, and modify `download.php` to check if the download flag for the gene is set and filter non-public columns and records if needed.

**Comment by mkroon1** [comment]
Btw, this issue is marked as a duplicate, but it's still linked to the project for the next milestone. Is this the place to discuss progress?

**Comment by ifokkema** [comment]
Main issue is #78 :wink:
