### ISSUE TITLE
Viewlist entry count differs from what is displayed

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#176]
In the variants-affecting-transcripts viewlist, LOVD (sometimes?) shows a count for the total number of entries that is different from the entries that is actually shown. See image below for example:

![lovd_bug_20170124](https://cloud.githubusercontent.com/assets/17007949/22251646/dab6b5f2-e24b-11e6-821f-9aaadc16af11.png)

(Reported by Julia)

**Comment by ifokkema** [comment]
Related to #167.
