### ISSUE TITLE
Browser's password autofill fills wrong text field with username

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#180]
Object editing forms like `variants/0000040172?edit` ask for a password to confirm the modification. Some browser(s) fill the password field automatically when this feature is turned on. In some cases the username is also filled, but in the wrong text field (on this form there is no username field). 

This is reproduced in Chromium 55 on Linux.

**Comment by mkroon1** [comment]
This seems a reincarnation of #27. The problem appears to be that newer versions of Chrome ignore the fake username field when it has `display: none` as style.

I have a fix ready in e032f95 where the fake username field is hidden (rather clumsily) with `width`, `visibility` CSS settings. I've tested it on Chromium 57 and FF 50, but I consider it still open for improvement.

**Comment by ifokkema** [comment]
Closed in 82e58a9.
