### ISSUE TITLE
Panel size description could be improved

### ISSUE THREAD

**Issue by jtdendunnen** [LOVDnl/LOVD3#191]
on the submission form, Individual, the text linked to the **Panel size** could be improved. I suggest:

Number of individuals this entry represents; e.g. 1 for an individual, 5 for a family with 5 affecteds. To report different Individuals from one family link them using the field "ID of panel this entry belongs to".

**Comment by mkroon1** [comment]
Fix is ready in PR #267. See PR comments for final text on form and viewlist (slight change).
