### ISSUE TITLE
Individual with many diseases takes up much space in viewlist.

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#193]
In an individuals-viewlist, a record with many diseases linked, will take up much space. Example:

![individual_many_diseases](https://cloud.githubusercontent.com/assets/17007949/23255874/741b897e-f9bd-11e6-96b9-a838abb7a2f1.png)

**Comment by mkroon1** [comment]
This issue doesn't seem to exist anymore. IIRC issue #192 prompted this, but it was caused by a mistake causing more than 2000 diseases to be linked to one individual -- which is not normal use of the LOVD software.

Propose not to fix this.

**Comment by ifokkema** [comment]
Agreed, closing this now.
