### ISSUE TITLE
Overview of variants with multiple classifications

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#202]
The view `variants/GENE/unique` shows variants with possibly multiple classifications (column "effect") grouped together. Of these, the ones with multiple (and possibly contradictory) classifications are of most interest, as they depict variants that may require attention.

However, it is not possible to get an overview of the variants with multiple classifications. For instance, [searching for `,` in the "effect" column in the view mentioned above](http://databases.lovd.nl/shared/variants/ABCA4/unique#object_id=VariantOnTranscriptUnique%2CVariantOnGenome&id=ABCA4&order=VariantOnTranscript%2FDNA%2CASC&skip[chromosome]=chromosome&skip[allele_]=allele_&skip[transcriptid]=transcriptid&search_transcriptid=00001847&skip[owner_countryid]=owner_countryid&FRMatchType_CustomVL_VOTunique_VOG_ABCA4=1&FRMatchType_CustomVL_VOTunique_VOG_ABCA4=2&FRMatchType_CustomVL_VOTunique_VOG_ABCA4=3&FRReplaceAll_CustomVL_VOTunique_VOG_ABCA4=1&=Preview&=Cancel&=Submit&search_vot_effect=%2C&page_size=100&page=1) to see only the rows with multiple values for that column does not yield the desired result.

**Comment by ifokkema** [comment]
I'd prefer a more flexible solution, allowing any conflicting values to be dug up by users, for instance in the exon or DBID fields, or less problematic; RNA or protein change.

In principle that would be a `HAVING` after the `WHERE`, and we can't use the default LOVD search fields for that, since they are connected to `WHERE`. Perhaps a simple `HAVING COUNT(DISTINCT col) > 1`? That should show any conflicts... The user then needs to select the column where he wants to see conflicting values, perhaps available from the options wheel?

**Comment by mkroon1** [comment]
That sounds like a good solution. Concerning the user interaction, are you thinking about the following?
* User navigates to page with viewlist containing aggregated column of possibly different values.
* User clicks options menu (gear icon) of viewlist.
* User clicks menu item "only view records with conflicting values for column X" (or something similar).
* Viewlist gets refreshed with HAVING condition active.

**Comment by ifokkema** [comment]
Yes, exactly!

> User clicks menu item "only view records with conflicting values for column X" (or something similar).

This part we'll need to figure out. Do you think we can lift out the part of the JS library that allows you to select a column for F&R and use it for this feature?

**Comment by mkroon1** [comment]
Yes, I think we should be able to re-use that code without too much trouble. But if there's only one or two columns to select, I think that's less user friendly than having a menu item specific to a particular column.
