### ISSUE TITLE
Link to Exon/Intron table missing on gene homepage

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#207]
The refseq parser creates an exon table HTML file. For example: [http://databases.lovd.nl/shared/refseq/A1BG_NM_130786.3_table.html](http://databases.lovd.nl/shared/refseq/A1BG_NM_130786.3_table.html).
However, this file is not linkable on the gene homepage. LOVD2 did provide this option.

**Comment by jtdendunnen** [comment]
Please note the link is present: Exon/intron information.  I missed it as well, maybe because the link behind it, listing the reference transcript, is misleading. Change link to "E/I table NM_xxxxxx" ?

**Comment by mkroon1** [comment]
> Change link to "E/I table NM_xxxxxx" ?

I've created a pull request (#211). If @ifokkema concurs with this change, he may merge it into master.
