### ISSUE TITLE
Support multiple genome builds

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#244]
It should be possible to have multiple active genome builds. This allows for installations to migrate towards a newer genome build with less effort.

Some considerations:
* Source variant description should be conserved. Making it possible to always go back to the content originally submitted.
* Optionally, genome builds may be deprecated -- only showing fields for those on edit forms when they contain data.
* ...?

More specifications needed.

**Comment by ifokkema** [comment]
Closing; work is continuing in #550.
