### ISSUE TITLE
Import file parsing fails with a fatal error when the diseaseid field is left empty for a phenotype record

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#245]
Import file parsing fails with a fatal error when the diseaseid field is left empty for a phenotype record.

`Fatal error: Call to a member function getForm() on null in import.php on line 850.`

getForm() should not be run if we don't have an disease ID.

**Comment by mkroon1** [comment]
Attaching test file to reproduce this issue: [test.lovd.txt](https://github.com/LOVDnl/LOVD3/files/1270271/test.lovd.txt)
