### ISSUE TITLE
List of installations on version 2.0 on website.

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#246]
On the [LOVD website](http://www.lovd.nl), one is automatically directed to the latest (3.0) homepage. Clicking "Public list of LOVD installations" lets the user go to an older version (2.0) of the homepage. Even though the page also lists LOVD3 installations.

It would be less confusing if clicking "Public list of LOVD installations" lets one stay on the latest version of the homepage.

**Comment by ifokkema** [comment]
The LOVD 3.0 website now has this list of LOVD installations as well:
http://www.lovd.nl/3.0/public_list

Also related; the manual lists the 2.0 URL as well, and should list the 3.0 URL.

**Comment by ifokkema** [comment]
The manual is fixed in fe5d29f.
