### ISSUE TITLE
Show LOVD is an IRDiRC recognized resource

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#248]
LOVD is an [IRDirC recognized resource](http://www.irdirc.org/activities/irdirc-recognized-resources/). There is a [logo](https://i0.wp.com/www.irdirc.org/wp-content/uploads/2016/06/LOGO_IRDIRCRR_RVB_big-tick.jpg?resize=500%2C278) that can be shown to notify visitors of this fact. It would be good to find a place on the lovd.nl homepage and/or shared installation for this logo.

**Comment by ifokkema** [comment]
Has been implemented already on the website some time ago, so closing this issue.
