### ISSUE TITLE
VariantOnGenome/DNA	field in lovd_variants table too small by default

### ISSUE THREAD

**Issue by woook** [LOVDnl/LOVD3#251]
This field is set to 100 characters but it's not too uncommon to have a variant that is too big for this. 
Could this be increased by default as I think that would be useful for new users?

e.g. g.47942184_47942185insATTAAATGAAGTCATGTATGGGACTTGCTTGGTTTAGCATCCAAAGCACAATGAACAGGGTTATTAGATGGATGTTGTGAGA

**Comment by ifokkema** [comment]
Hi Wook,

Are you referring to LOVD or LOVD+? In LOVD+, the conversion script shortens the DNA description in long insertions when the variant description is longer than 100 characters. In the version of LOVD+ installed in your institution, there is a minor bug that makes it sometimes skip this shortening step. Did you run into this issue?

In normal LOVD, we would describe your variant as:
`g.47942184_47942185ins(61)`

Cheers,
Ivo

**Comment by woook** [comment]
Hi Ivo - this is for LOVD3.
I'm imported a VCF via the `only submit variant summary` function in the `Submit` menu that included that insertion, and got an error message saying that the field size was too small?

**Comment by ifokkema** [comment]
Ah, OK. For now, you can increase the size of the field to anything you like through the Setup area (see the manual). It wouldn't hurt much to increase the default size to 150 characters, though. I'll leave this open until we make this change.
