### ISSUE TITLE
Gene symbol filter on public list of LOVD installations not working

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#254]
The "List of public LOVD installations" on the lovd.nl website has a little form to filter the entries based on whether they contain a given gene symbol. This filter does not seem to work, for example filling out `MECP2` leads the user to http://www.lovd.nl/3.0/public_list/MECP2 where installations are listed that contain zero genes.

**Comment by ifokkema** [comment]
Hmm... had been shuffling code around, and that broke the implementation. Thanks, fixed now!
