### ISSUE TITLE
Additional variant effect values

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#261]
There is need for additional variant effect values. Currently, when a variant does have an effect on the function of the gene, but may not cause disease or may not cause the disease associated with the individual in which the variant is reported, it is debatable which variant effect should be selected. Therefore, it is proposed to add two additional values.

The currently active effects:

| Code | ID | Description |
|---|:-:|---|
| . | 0 | Not classified |
| ? | 5 | Variant effect unknown |
| + | 9 | Variant affects function |
| +? | 7 | Variant probably affects function |
| -? | 3 | Variant probably does not affect function |
| - | 1 | Variant does not affect function |

It is proposed to add:

| Code | ID | Description |
|---|:-:|---|
| # | 6 | Variant affects function but was not associated with any known disease phenotype |
| +* | 8 | Variant affects function but was not associated with this individual's disease phenotype |

To be determined:
- Perhaps the description of # should read "disease" instead of "disease phenotype"?
- What to do with these values in the API?
  - Translate `#` to `-` to indicate it's not disease-causing, or add as separate value that might not fit in other system's 5-class lists?
  - Translate `+*` to `+` to indicate it's disease causing, or add as separate value that might not fit in other system's 5-class lists?

**Comment by jtdendunnen** [comment]
For background information people could check http://varnomen.hgvs.org/bg-material/basics/ under terminology. Based on these recommendations LOVD does not use "pathogenic".

**Comment by jtdendunnen** [comment]
Agree with the proposal but suggest 8 = Variant affects function but was not associated with the DISEASE phenotype.

**Comment by ifokkema** [comment]
> (...) but suggest 8 = Variant affects function but was not associated with the DISEASE phenotype.

I've changed them both to read "disease phenotype" now, it makes more sense indeed.

**Comment by maximilianh** [comment]
These labels are good for humans, but not so good for machines. Ivo asked me how these should be encoded. These long descriptions are not so suitable for computer<->computer communication. Usually, values like these are shortened to strings that easy to memorize.

Here are my suggestions:

Not classified -> noClass
Variant effect unknown -> unknown
Variant affects function -> func
Variant probably affects function -> probFunc
Variant probably does not affect function -> probNoFunc
Variant does not affect function -> noFunc
Variant affects function but was not associated with any known disease phenotype -> funcNoPheno
Variant affects function but was not associated with this individual's disease phenotype -> funcNoIndivPheno



? | 5 | Variant effect unknown
+ | 9 | Variant affects function
+? | 7 | Variant probably affects function
-? | 3 | Variant probably does not affect function
- | 1 | Variant does not affect function

**Comment by ifokkema** [comment]
After more deliberation, the *machine readable* values are chosen to be:

```
0 => 'notClassified',
9 => 'functionAffected',
8 => 'notThisDisease',
6 => 'notAnyDisease',
7 => 'functionProbablyAffected',
3 => 'functionProbablyNotAffected',
1 => 'functionNotAffected',
5 => 'unknown',
```
