### ISSUE TITLE
The page header isn't properly displayed when system logo is changed.

### ISSUE THREAD

**Issue by crirocha** [LOVDnl/LOVD3#277]
The page header isn't properly displayed when system logo is changed, if the image is bigger than the original logo we cant access the features links.
e.g.:http://bipmed.iqm.unicamp.br/LOVD/genes

**Comment by ifokkema** [comment]
Hi,
Could you tell us which LOVD version you are running? On your installation it says 3.0-17, but that is not 3.0-17 code. Have you copied only part of an LOVD update? Or have you copied all the files, but you haven't logged in? Please note that to complete an upgrade, you have to log in to LOVD as manager or higher. That may not fix your problem, but it will fix a lot of other issues, and will allow us to help you better.

**Comment by mkroon1** [comment]
I verified this problem in the latest version. I'll schedule to fix it for the next release.
