### ISSUE TITLE
Upgrade Travis environment and simplify setup

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#284]
Currently we run continuous integration on a deprecated environment of Travis, as specified in `.travis.yml`:

    group: deprecated-2017Q2

This environment will not be around forever (predicted resignation of this env is this month, september 2017). Therefore it's necessary to upgrade soon and make sure our tests work with the latest environment based on Ubuntu 14.04. I think a good target would be the environment that will be released this afternoon ([2017-09-06](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/)).

This is also a great opportunity to scrutinize the build scripts and try to improve or simplify them. Some potential improvements:

- [ ] Use mysql 5.7 (instead of currently used 5.6) + make sure `strict_mode` is on.
- [x] `/tests/travis/setup/setup_chrome.sh`
  - [x] Move installation of dependencies using `apt-get` to `.travis.yml`'s `apt` directive.
  - [x] Try to avoid running `xvfb` by using chrome's new headless mode.
- [ ] `/tests/travis/setup/setup_apache.sh`
  - [x] Move installation of dependencies using `apt-get` to `.travis.yml`'s `apt` directive.
  - [x] Remove unnecessary php dependencies.
  - [ ] Simplify argument parsing.
- [x] `/tests/travis/setup/setup_selenium.sh`
  - [x] Get selenium working with the newer versions of the browsers and drivers.
  - [x] Remove xvfb stuff that's not used anyway.

**Comment by mkroon1** [comment]
I'll put this issue on hold for the moment. The Travis [trusty environment](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/) that should be active right now has Firefox 55. But the [job I recently started](https://travis-ci.org/LOVDnl/LOVD3/jobs/272790287#L529) is still stuck on Firefox 50. Trying to get it to work currently would be aiming for a moving target.

**Comment by ifokkema** [comment]
Closed in #336.
