### ISSUE TITLE
No proper warnings when deleting a gene or a disease

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#29]
From Trello:
> When deleting a gene, all VOT (VariantOnTranscript) entries are removed. When deleting a disease, all phenotype entries are removed. The latter is not mentioned when deleting a disease. And both forms just ask for the password once, while LOVD2 used to ask for double confirmation.

- [x] Download the LOVD2 code, and check setup_genes.php. Look for the code that handles the $_GET['drop'] variable, and you'll find the code that handles deleting a gene. Note how a second variable, $_GET['confirm'], is used to make the user think twice about deleting the gene.
- [x] LOVD3 is slightly different, variants are not removed, but their mapping on the gene is removed. This warning is already present. Now, implement the double form method in LOVD3 as well, and display on that page the number of variants that will lose their mapping to this gene.
- [x] Add to the page that deletes a disease a similar warning that the gene removal form already has, about all phenotypes being removed.
- [x] Implement the double form method for deleting a disease, too.

**Comment by mkroon1** [comment]
I've investigated the LOVD2 code. It seems that a user has to fill out their password twice. Isn't that a bit overkill? I agree it's useful to have a second warning/confirmation for potentially destructive actions. But a second password request is not going to stop people from making mistakes, but it does add annoyance.

**Comment by ifokkema** [comment]
Hmm... we never had a user complain about it, to be honest. For me, when a form asks me for my password twice, it's a reminder that what I'm doing might be quite destructive. And users hardly will need to remove a gene or a disease, so I don't think we need to change that behaviour from LOVD2 to LOVD3.
