### ISSUE TITLE
ORCID returning ID not found error when creating new user

### ISSUE THREAD

**Issue by jplazzer** [LOVDnl/LOVD3#340]
The user's ORCID exists, but LOVD is not able to retrieve it:

"The given ORCID ID can not be found at ORCID.org. "

**Comment by ifokkema** [comment]
We're hit by this:
https://groups.google.com/forum/#!msg/orcid-api-users/d0d98f0OcIw/rWMP1y9KBgAJ

We'll need to upgrade our API usage.

**Comment by ifokkema** [comment]
Closed by #344.
