### ISSUE TITLE
Test fails due to timeout

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#35]
Tests (Selenium) sometimes fail due to time-out problems. It also affects Travis, for example in [this branch](https://travis-ci.org/LOVDnl/LOVD3/builds/111166987) where none of the LOVD core code was touched.

I think we should increase the default time a test waits for response, as we can't predict the load on Travis' servers. Now it's 30 seconds, we can make it 60 seconds. PHP's *max_execution_time* probably has to be increased then accordingly.

**Comment by ifokkema** [comment]
Agreed. But to be honest, I doubt we'll run into problems with PHP timing out. If we have stuff running that can really take that long, LOVD would have already taken care of things. So I'm pretty sure we can just adapt the selenium tests, and be done with it.

**Comment by ifokkema** [comment]
Depends on #72.
