### ISSUE TITLE
Message report error links to old ticket system. 

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#42]
When LOVD encounters a database error, it shows a message like below. Linking to the old trac ticket system. Expected behavior is to refer users to the github LOVD3 issues page https://github.com/LOVDnl/LOVD3/issues

> A failed query is usually an LOVD bug. Please report this bug by copying the above text and send it to us by opening a new ticket in our [bug tracking system](https://humgenprojects.lumc.nl/trac/LOVD3/newticket).

**Comment by ifokkema** [comment]
Ha, good one! Totally forgot about that link... thanks, I merged the PR!
