### ISSUE TITLE
API not returning EXT2 result for primary transcript that is present in UI

### ISSUE THREAD

**Issue by sptaylor** [LOVDnl/LOVD3#420]
A variant exists for gene EXT1 position/change c.1780G>C, but when I use the API, I get no results returned for the primary transcript (NM_000401.3)

API call with no results:
https://databases.lovd.nl/shared/api/rest.php/variants/EXT2?search_Variant/DNA=c.1780G%3EC

Variant listed in UI:
https://databases.lovd.nl/shared/variants/0000613336#00007321

If I search using the DNA position for the alternate transcript (NM_207122.1), I get a result:
https://databases.lovd.nl/shared/api/rest.php/variants/EXT2?search_Variant/DNA=c.1681G%3EC

View of the result in the UI
![image](https://user-images.githubusercontent.com/909335/84415152-325cb700-abc7-11ea-8c19-cb4388e2975f.png)

View of the detail result page, showing mapping to both transcripts:
![image](https://user-images.githubusercontent.com/909335/84415195-43a5c380-abc7-11ea-8dd3-63b197e83eb6.png)

**Comment by ifokkema** [comment]
Hi Paige,

Unfortunately, the current API is quite limited and it exports only the variants of *one* transcript. I want to build a new API (JSON based) this year. Either way, recently, I changed the code of the API to use the transcript that has the most variants. In the case of _EXT2_, this is NM_207122.1 (having 432 variants) and not NM_000401.3 (having 45 variants). I'm not an expert on the _EXT2_ gene, so I don't know why these submitters chose to submit their data to the other transcript, but apparently they thought it was more relevant than NM_000401.3.

Now, as possible solutions;
- If you want to search on transcript-based positions and you first want to know which transcript the API will use, you can request https://databases.lovd.nl/shared/api/rest.php/genes/EXT2 and read out the first transcript in the `refseq_mrna` field.
- You can search for the genomic position instead, always getting a hit no matter which transcript has been selected: https://databases.lovd.nl/shared/api/rest.php/variants/EXT2?search_position=g.44253921
- If you believe all variants should be mapped to NM_000401.3, instead, we can contact the _EXT2_ curator and discuss this with him.

**Comment by sptaylor** [comment]
Thank you, this is helpful!

Is it possible to have the "primary" transcript (in this case, NM_207122.1 by virtue of more variant annotations) be the primary one returned in the UI? e.g., this link https://databases.lovd.nl/shared/variants/EXT2?search_VariantOnTranscript%2FDNA=c.1234C%3ET opens up the results for the non-primary transcript by default. To see NM_207122.1 results, you must toggle the transcript button or engineer the link to include the transcript:
https://databases.lovd.nl/shared/variants/EXT2/NM_207122.1?search_VariantOnTranscript/DNA=c.1234C%3ET

**Comment by ifokkema** [comment]
That's a very good point, thank you. The interface and the API now sort the transcripts differently. I'll look into it tomorrow!

**Comment by ifokkema** [comment]
Hi Page,
Thanks again for your report, I have fixed the sorting issue in the GUI and have updated the GV shared LOVD instance.
Have a great day!

**Comment by ifokkema** [comment]
By the way, @sptaylor, I completely forgot;
Your first link will actually work if you add the `format=application/json` flag to it; our JSON API output does not group on the most-used transcript like our "old" Atom format API does. This might also be much easier to parse.

> API call with no results:
> https://databases.lovd.nl/shared/api/rest.php/variants/EXT2?search_Variant/DNA=c.1780G%3EC

Try https://databases.lovd.nl/shared/api/rest.php/variants/EXT2?search_Variant/DNA=c.1780G%3EC&format=application/json, which does return results.

Sorry for that late epiphany, sometimes even I forget what my own code does.

**Comment by sptaylor** [comment]
Thank you!! This is perfect.
