### ISSUE TITLE
Viewlist of submissions for user does not link anywhere

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#43]
Page `users/USER_ID?submissions` shows a viewlist of unfinished submissions. Clicking rows in the viewlist does nothing. Desirable behavior is to click a row in the viewlist and be directed to a page related to that particular submission.

[Example on shared installation(2016-03-16)](http://databases.lovd.nl/shared/users/00573?submissions)

(Noticed by Johan)

**Comment by ifokkema** [comment]
But... if you're the actual owner, you do have links and it does lead to a page that can be used to finish the submission. It wouldn't make much sense for allowing somebody else to enter that submission process, right? Did a user mention missing links?
Or is Johan's request specifically for non-owners? Then we could add links for non-owners to the normal VE?
