### ISSUE TITLE
LOVD2 converter: Warning: linked "Variant/DbSNP" to non-existing column "VariantOnTranscript/DbSNP" in output section "Variants_On_Transcripts".

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#437]
Reported by Wei Kheng Teh;
While converting an LOVD2 file to the LOVD3 format:
```
Warning: linked "Variant/DbSNP" to non-existing column "VariantOnTranscript/DbSNP" in output section "Variants_On_Transcripts".
```
This should be mapped to `VariantOnGenome/dbSNP`.

**Comment by Wkt8** [comment]
### LOVD-version 2000-360 ### Variants/Patients ### Do not remove this line, unless importing in versions before 2.0-04 ###

"{{ Variant/Exon }}"	"{{ Variant/DNA }}"	"{{ Variant/DbSNP }}"	"{{ Variant/Type }}"	"{{ Variant/Consequence/Predicted }}"	"{{ Variant/Protein }}"	"{{ Variant/RNA }}"	"{{ Variant/Restriction_site }}"	"{{ Variant/Frequency }}"	"{{ Variant/DBID }}"	"{{ Patient/Patient_ID }}"	"{{ Patient/Phenotype/Disease }}"	"{{ Patient/Reference }}"	"{{ Patient/Detection/Template }}"	"{{ Patient/Detection/Technique }}"	"{{ Patient/Remarks }}"	"{{ Patient/Remarks_Non_Public }}"	"{{ Patient/Origin/Ethnic }}"	"{{ ID_variantid_ }}"	"{{ ID_patientid_ }}"	"{{ ID_allele_ }}"	"{{ ID_pathogenic_ }}"	"{{ ID_status_ }}"	"{{ ID_sort_ }}"	"{{ ID_submitterid_ }}"	"{{ ID_variant_created_by_ }}"	"{{ variant_created_date_ }}"	"{{ ID_variant_edited_by_ }}"	"{{ variant_edited_date_ }}"	"{{ ID_patient_created_by_ }}"	"{{ patient_created_date_ }}"	"{{ ID_patient_edited_by_ }}"	"{{ patient_edited_date_ }}"
"01"	"c.2T>C"	""	"substitution"	"initiating methionine"	"p.?"	""	""	""	"ADAMTS2_00008"	"AN_001995"	"Dermatosparaxis EDS"	"{PMID26765342:Van Damme et al., 2016}"	"DNA"	"PCR;SEQ"	""	""	""	"0000010"	"0001462"	"11"	"99"	"9"	"0001_0000002_0000000"	"00004"	"0"	"2015-07-31 10:21:53"	"1"	"2015-11-16 14:52:31"	"0"	"2015-07-31 10:21:53"	"1"	"2016-01-18 16:34:30"
"01"	"c.102_123dup"	""	"duplication"	"frameshift"	"p.Ala42Argfs*31"	""	""	""	"ADAMTS2_00018"	" "	""	"{PMID31939527:Bo et al., 2020}"	"DNA"	"WES"	"The patient was diagnosed with situs inversus totalis, and idiopathic thrombocytopenia purpura. The variant was described in the paper as an insertion at c.123_124, but is in fact a duplication of c.102_123. It was detected via exome sequencing, and thus the authors were uncertain if the patient had compound heterogeneity for another variant in ADAMTS2. "	""	""	"0000020"	"0001841"	"0"	"11"	"9"	"0001_0000102_0000000_0000123_0000000"	"00000"	"9"	"2020-05-11 16:38:18"	"9"	"2020-05-11 16:38:24"	"9"	"2020-05-11 16:38:18"	"9"	"2020-05-11 16:39:24"

**Comment by Wkt8** [comment]
### LOVD-version 2000-360 ### Variants/Patients ### Do not remove this line, unless importing in versions before 2.0-04 ###
"{{ Variant/Exon }}"	"{{ Variant/DNA }}"	"{{ Variant/DbSNP }}"	"{{ Variant/Type }}"	"{{ Variant/Consequence/Predicted }}"	"{{ Variant/Protein }}"	"{{ Variant/RNA }}"	"{{ Variant/Restriction_site }}"	"{{ Variant/Frequency }}"	"{{ Variant/DBID }}"	"{{ Patient/Patient_ID }}"	"{{ Patient/Phenotype/Disease }}"	"{{ Patient/Reference }}"	"{{ Patient/Detection/Template }}"	"{{ Patient/Detection/Technique }}"	"{{ Patient/Remarks }}"	"{{ Patient/Remarks_Non_Public }}"	"{{ Patient/Origin/Ethnic }}"	"{{ ID_variantid_ }}"	"{{ ID_patientid_ }}"	"{{ ID_allele_ }}"	"{{ ID_pathogenic_ }}"	"{{ ID_status_ }}"	"{{ ID_sort_ }}"	"{{ ID_submitterid_ }}"	"{{ ID_variant_created_by_ }}"	"{{ variant_created_date_ }}"	"{{ ID_variant_edited_by_ }}"	"{{ variant_edited_date_ }}"	"{{ ID_patient_created_by_ }}"	"{{ patient_created_date_ }}"	"{{ ID_patient_edited_by_ }}"	"{{ patient_edited_date_ }}"
"01"	"c.2T>C"	""	"substitution"	"initiating methionine"	"p.?"	""	""	""	"ADAMTS2_00008"	"AN_001995"	"Dermatosparaxis EDS"	"{PMID26765342:Van Damme et al., 2016}"	"DNA"	"PCR;SEQ"	""	""	""	"0000010"	"0001462"	"11"	"99"	"9"	"0001_0000002_0000000"	"00004"	"0"	"2015-07-31 10:21:53"	"1"	"2015-11-16 14:52:31"	"0"	"2015-07-31 10:21:53"	"1"	"2016-01-18 16:34:30"
"01"	"c.102_123dup"	""	"duplication"	"frameshift"	"p.Ala42Argfs*31"	""	""	""	"ADAMTS2_00018"	"-"	""	"{PMID31939527:Bo et al., 2020}"	"DNA"	"WES"	"The patient was diagnosed with situs inversus totalis, and idiopathic thrombocytopenia purpura. The variant was described in the paper as an insertion at c.123_124, but is in fact a duplication of c.102_123. It was detected via exome sequencing, and thus the authors were uncertain if the patient had compound heterogeneity for another variant in ADAMTS2. "	""	""	"0000020"	"0001841"	"0"	"11"	"9"	"0001_0000102_0000000_0000123_0000000"	"00000"	"9"	"2020-05-11 16:38:18"	"9"	"2020-05-11 16:38:24"	"9"	"2020-05-11 16:38:18"	"9"	"2020-05-11 16:39:24"
"02"	"c.220G>A"	"{dbSNPrs2271211}"	"substitution"	"missense"	"p.Val74Met"	""	""	""	"ADAMTS2_00014"	"-"	"DAD"	"{PMID32095376:Chen et al., 2020}"	"DNA"	"WES;WGS"	"This deleterious SNP is highly associated with intracranial aneurysm. "	""	"Han Chinese"	"0000016"	"0001837"	"0"	"11"	"9"	"0002_0000220_0000000"	"00000"	"9"	"2020-05-05 15:25:45"	"9"	"2020-05-05 15:30:48"	"9"	"2020-05-05 15:25:45"	"9"	"2020-05-05 15:26:02"
