### ISSUE TITLE
Fix link to NCBI sequence viewer

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#439]
Reported by @jbychang, see #435.
The UCSC genome browser link has been fixed, but the NCBI sequence viewer link still needs work. It currently shows an error that the URL is not accessible.

See this [example link](https://www.ncbi.nlm.nih.gov/projects/sviewer/?id=NC_000017.10&v=29421845:29704795&content=7&url=http%3A%2F%2Fdatabases.lovd.nl%2Fshared%2Fapi%2Frest%2Fvariants%2FNF1%3Fformat%3Dtext%2Fbed).

**Comment by jbychang** [comment]
Beautiful. Thank you!
