### ISSUE TITLE
lovd.nl api version

### ISSUE THREAD

**Issue by peq123** [LOVDnl/LOVD3#447]
Hi @ifokkema 

I had a meeting with Pete (VariantValidator) in which there was a discussion about the data available through the LOVD api. He was under the impression that more of the data in the version 3 database was accessible via the api. Once such case was the functional information about a variant that was available via the website but I did not see a way to access it via the api . I have used the url listed in the documentation pdf, which seems to only expose a limited amount of information. 

Could you please confirm the version of LOVD that the api uses and whether or not there are methods to retrieve the functional information? The requesting url I have been using is below:

https://databases.lovd.nl/shared/api/rest.php/variants/BRCA1?format=application/json

Thank you 

peq123

**Comment by ifokkema** [comment]
Hi @peq123,

Pete's right, and the documentation isn't fully updated yet. Although the current APIs are still rather rudimentary and we're planning to build a much more advanced API soon, for the full list of options, please see the [source file's header](https://github.com/LOVDnl/LOVD3/blob/7901efaf200329c842145d53218f1b0ef28c5e37/src/api.php#L10-L32). Specifically, you're looking for the `show_variant_effect` flag.

We're really hoping to have a new API for testing in ~6 months or so.
