### ISSUE TITLE
cann't add or register new user account

### ISSUE THREAD

**Issue by pengchy** [LOVDnl/LOVD3#495]
Dear LOVD developers,

Thank you for your excellent platform. I have installed LOVDv.3.0-25.tar.gz at http://121.36.9.191/LOVDv.3.0/.

  When I login as administrator, 1) I cann't create new user as manager or submitter through http://121.36.9.191/LOVDv.3.0/users?create , the LOVD said (_The 'Level' field is limited to numbers no higher than_ .); 2) there are only two levels, manager and submitter .
![lovd-register-create](https://user-images.githubusercontent.com/1439962/106106207-29355000-6180-11eb-9004-57bc6ef29bf4.png)

  When I try to register as submitter through http://121.36.9.191/LOVDv.3.0/users?register, after fill all the required information, the registering is failed and LOVD said (_Registration authentication failed. Please try again by checking the checkmark and following the instructions at "Please verify that you are not a robot" at the bottom of the form._). 

![lovd-register](https://user-images.githubusercontent.com/1439962/106105831-95fc1a80-617f-11eb-93f2-be8a64775f34.png)

Please help me out.
Thank you.

**Comment by ifokkema** [comment]
Hi @pengchy,

The first error can only happen when the installation has been broken in a certain way. So either the installation never completed, the database was modified, the code was modified, or there's something very wrong with your server's settings. It's impossible for me to see which one applies. I can not reproduce this error in any way.

The second error happens in China, where the Google plugin that we use to protect against spam registrations, is blocked. I'll work in the future on making that plugin a setting because it doesn't seem China will unblock that plugin. That does create a much higher chance of spam registrations, but there's still another plugin present in LOVD3 that should then hopefully still keep most spam registrations out.

**Comment by ifokkema** [comment]
Hi again, I see Google has a solution for the plugin not working in China. Can you confirm the following two links for me, please?
- This link does *not* work: https://www.google.com/recaptcha/api.js
- This link *does* work: https://www.recaptcha.net/recaptcha/api.js

**Comment by pengchy** [comment]
Hi @ifokkema,

The second link work: https://www.recaptcha.net/recaptcha/api.js

**Comment by ifokkema** [comment]
Thanks, I have created a fix for the "Registration authentication failed" error. The first error I, unfortunately, can not trace.

Once my automated tests complete, I'll merge the changes into master and you can pull these in to fix the registration problem.

**Comment by pengchy** [comment]
Hi @ifokkema :

Thank you for your work on this problem. To resolve the problem of "is limited to numbers no higher than", I have tested several versions of LOVD, including version 22, 23, and 25. However, although I can successfully install them, but I failed to add one new user account or add a customized column for Individual or Variant. The error message is always "The 'Column display width in pixels' field is limited to numbers no higher than .". I am stuck on this problem for these days.

I have checked the code that produced this error message. I found this error message is produced by the source code file "class/objects.php" line 529. So, could you please help me check this problem?

The attachment is the httpd.conf file for apache.
[httpd.conf.txt](https://github.com/LOVDnl/LOVD3/files/5903837/httpd.conf.txt)

Thank you.

**Comment by ifokkema** [comment]
Hi @pengchy ,

Unfortunately, I can't tell from your `httpd.conf` what's wrong - a server's configuration is distributed among at least dozens of different configuration files.

In the code you mention, it seems from the error message that `$nMaxLength` is set to `0`. That means that the `lovd_getColumnLength()` function does not seem to work well. This almost certainly means that that the `lovd_getColumnData()` function doesn't seem to work. That almost certainly means that your database is somehow not responding properly to the `SHOW COLUMNS FROM tablename` command (see `inc-lib-init.php`, line 549). If you can, it would be great if you could run that command in SQL, so we can see what's going on. For instance: 

```
SHOW COLUMNS FROM lovd_user;
```
(the table name depends on the table prefix as set in your config.ini.php file)

**Comment by pengchy** [comment]
Hi @ifokkema ,

Thank you for your reply.
The content of `SHOW COLUMNS FROM lovd_users;` is demonstrated below. It seems the lovd_users table is normal.

![lovd_users](https://user-images.githubusercontent.com/1439962/106469698-96c3e200-64da-11eb-849c-5c051d597893.png)

**Comment by ifokkema** [comment]
This output looks good, indeed.
Could you place a new file in the root of your LOVD directory with this content:

```php
<?php
header('Content-type: text/plain');
define('ROOT_PATH', './');
require ROOT_PATH . 'inc-init.php';
var_dump('Requesting column information from Variants table', lovd_getColumnData(TABLE_VARIANTS));
var_dump('Requesting maximum length of DNA column', lovd_getColumnLength(TABLE_VARIANTS, 'VariantOnGenome/DNA'));
?>
```

Then access the file in your browser, and paste the results, please?

**Comment by pengchy** [comment]
The output page is attached below for adding one customized column for Individual:
![image](https://user-images.githubusercontent.com/1439962/106533669-96a10200-652d-11eb-80d7-78584f0c4533.png)

The output page is attached below for adding one customized column for Variants:
![image](https://user-images.githubusercontent.com/1439962/106533963-0911e200-652e-11eb-8eeb-cc405c6358a9.png)

**Comment by ifokkema** [comment]
Thank you, I just needed the output of the script, I found it at http://121.36.9.191/LOVDv.3.0/test.php. You can remove it again.

So all the functions work well, so again this means that there's something very strange with your LOVD instance. Are you sure you didn't change any of the code? If not, please edit `/class/objects.php`, and find this line:
```php
lovd_errorAdd($sFieldname, 'The \'' . $sHeader . '\' field is limited to numbers no higher than ' . str_repeat('9', $nMaxLength) . '.');
```

Above or below that line, please add:
```php
var_dump($this->sTable, constant($this->sTable), $sFieldname, $sNameClean, $sMySQLType, $nMaxLength);
```

When you then try to create a new column, you'll get more text on the top of the screen. Can you please send me that text?
It should look something like:
```
string(10) "TABLE_COLS" string(15) "lovd_columns" string(5) "width" string(5) "width" string(12) "INT_UNSIGNED" int(5)
```

**Comment by pengchy** [comment]
Hi @ifokkema ,

Thank you. The output of this script is pasted below:
```
sTable lovd_columns
string(10) "TABLE_COLS" string(12) "lovd_columns" string(5) "width" string(5) "width" string(12) "INT_UNSIGNED" int(0)
```

**Comment by ifokkema** [comment]
I see, thank you.
Can you tell me what database backend you are using, and what version?

**Comment by pengchy** [comment]
Hi @ifokkema ,
Thank you. the `mysql --version` said:
`mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)`

**Comment by pengchy** [comment]
Hi @ifokkema ,

I have tested successfully with MySQL version 5.7. The above mentioned problem is caused by MySQL version 8.0.

Thank you.
Best,
Pengcheng

**Comment by ifokkema** [comment]
Hi @pengchy ,

Thanks a lot for letting me know! I will leave this open until I have developed a fix. Of course, LOVD should also be compatible with MySQL 8.

**Comment by ifokkema** [comment]
Hi @pengchy,
Thank you for your report - I have created a fix. I will release 3.0-26 later, which will allow you to also use LOVD on MySQL 8.
