### ISSUE TITLE
'lovd3_whole_genome.lovd_v3_variants_on_transcripts' doesn't exist

### ISSUE THREAD

**Issue by camundsen** [LOVDnl/LOVD3#497]
It looks like there's some kind of dastabase problem going on with the endpoint 

https://databases.lovd.nl/whole_genome/api/rest.php/genes?search_symbol=BRCA2

/api/rest.php/genes?search_symbol=BRCA2 returned error in code block Unknown.Query : SELECT g.id, g.name, g.chromosome, g.chrom_band, MAX(t.position_g_mrna_start < t.position_g_mrna_end) AS sense, LEAST(MIN(t.position_g_mrna_start), MIN(t.position_g_mrna_end)) AS position_g_mrna_start, GREATEST(MAX(t.position_g_mrna_start), MAX(t.position_g_mrna_end)) AS position_g_mrna_end, g.refseq_genomic, GROUP_CONCAT(DISTINCT t.id_ncbi ORDER BY (SELECT COUNT(*) FROM lovd_v3_variants_on_transcripts WHERE transcriptid = t.id) DESC, t.id ASC SEPARATOR ";") AS id_ncbi, g.id_entrez, g.created_date, g.updated_date, u.name AS created_by, GROUP_CONCAT(DISTINCT cur.name SEPARATOR ";") AS curatorsFROM lovd_genes AS g LEFT OUTER JOIN lovd_transcripts AS t ON (g.id = t.geneid) LEFT OUTER JOIN lovd_users AS u ON (g.created_by = u.id) LEFT OUTER JOIN lovd_users2genes AS u2g ON (g.id = u2g.geneid AND u2g.allow_edit = 1) LEFT OUTER JOIN lovd_users AS cur ON (u2g.userid = cur.id)WHERE 1=1 AND g.id = "BRCA2" GROUP BY g.id ORDER BY g.idError : Error in PDO::query() while running query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lovd3_whole_genome.lovd_v3_variants_on_transcripts' doesn't exist | /api/rest.php/genes?search_symbol=BRCA2 returned error in code block Unknown.Query : SELECT g.id, g.name, g.chromosome, g.chrom_band, MAX(t.position_g_mrna_start < t.position_g_mrna_end) AS sense, LEAST(MIN(t.position_g_mrna_start), MIN(t.position_g_mrna_end)) AS position_g_mrna_start, GREATEST(MAX(t.position_g_mrna_start), MAX(t.position_g_mrna_end)) AS position_g_mrna_end, g.refseq_genomic, GROUP_CONCAT(DISTINCT t.id_ncbi ORDER BY (SELECT COUNT(*) FROM lovd_v3_variants_on_transcripts WHERE transcriptid = t.id) DESC, t.id ASC SEPARATOR ";") AS id_ncbi, g.id_entrez, g.created_date, g.updated_date, u.name AS created_by, GROUP_CONCAT(DISTINCT cur.name SEPARATOR ";") AS curatorsFROM lovd_genes AS g LEFT OUTER JOIN lovd_transcripts AS t ON (g.id = t.geneid) LEFT OUTER JOIN lovd_users AS u ON (g.created_by = u.id) LEFT OUTER JOIN lovd_users2genes AS u2g ON (g.id = u2g.geneid AND u2g.allow_edit = 1) LEFT OUTER JOIN lovd_users AS cur ON (u2g.userid = cur.id)WHERE 1=1 AND g.id = "BRCA2" GROUP BY g.id ORDER BY g.idError : Error in PDO::query() while running query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lovd3_whole_genome.lovd_v3_variants_on_transcripts' doesn't exist
-- | --
/api/rest.php/genes?search_symbol=BRCA2 returned error in code block Unknown.Query : SELECT g.id, g.name, g.chromosome, g.chrom_band, MAX(t.position_g_mrna_start < t.position_g_mrna_end) AS sense, LEAST(MIN(t.position_g_mrna_start), MIN(t.position_g_mrna_end)) AS position_g_mrna_start, GREATEST(MAX(t.position_g_mrna_start), MAX(t.position_g_mrna_end)) AS position_g_mrna_end, g.refseq_genomic, GROUP_CONCAT(DISTINCT t.id_ncbi ORDER BY (SELECT COUNT(*) FROM lovd_v3_variants_on_transcripts WHERE transcriptid = t.id) DESC, t.id ASC SEPARATOR ";") AS id_ncbi, g.id_entrez, g.created_date, g.updated_date, u.name AS created_by, GROUP_CONCAT(DISTINCT cur.name SEPARATOR ";") AS curatorsFROM lovd_genes AS g LEFT OUTER JOIN lovd_transcripts AS t ON (g.id = t.geneid) LEFT OUTER JOIN lovd_users AS u ON (g.created_by = u.id) LEFT OUTER JOIN lovd_users2genes AS u2g ON (g.id = u2g.geneid AND u2g.allow_edit = 1) LEFT OUTER JOIN lovd_users AS cur ON (u2g.userid = cur.id)WHERE 1=1 AND g.id = "BRCA2" GROUP BY g.id ORDER BY g.idError : Error in PDO::query() while running query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lovd3_whole_genome.lovd_v3_variants_on_transcripts' doesn't exist

**Comment by ifokkema** [comment]
Oops, thanks! I've created a fix and will deploy it soon.

**Comment by ifokkema** [comment]
Thanks again! I've deployed the fix.

**Comment by camundsen** [comment]
Thank you for the quick response!

- Craig
