### ISSUE TITLE
delete multiple individuals or other items in batch mode

### ISSUE THREAD

**Issue by pengchy** [LOVDnl/LOVD3#503]
Hi Ivo,

In order to uncheck the "Show contents to public" in the customized columns for individual, I have accidentally deactivated customized columns and removed the corresponding values of hundreds entries.  Now, after unchecking the "Show contents to public", I want to re-upload the table for individual table through "Import data in LOVD format" with "update existing data" option. However, this seems impossible, because the error message said that: "too many fields are different from the database .... There is a maximum of 1 difference to prevent accidental updates".

So, I would like to ask whether it possible to 1) delete individuals or other entries in batch mode; 2) update the existing tables for more than one difference.

Best,
Pengcheng

**Comment by ifokkema** [comment]
Hi Pengcheng,

> In order to uncheck the "Show contents to public" in the customized columns for individual, I have accidentally deactivated customized columns and removed the corresponding values of hundreds entries.

Do you mean you wanted to hide the columns from the public but instead removed the columns from the Individuals table? LOVD should have warned you about data getting lost - something like "Please note that this will permanently delete the data in this column. X values will be lost." - do you think this warning message should be improved?


> Now, after unchecking the "Show contents to public", I want to re-upload the table for individual table through "Import data in LOVD format" with "update existing data" option. However, this seems impossible, because the error message said that: "too many fields are different from the database .... There is a maximum of 1 difference to prevent accidental updates".

If only one column was changed, it should process the update without problems. So this indicates also other changes were found, and this is a high-risk procedure. Have you tried comparing a current LOVD download with your original (for instance, using a tool like "meld" (for Linux)), to verify if there aren't any other changes that you don't mean to process? If you're sure, you can edit `import.php` and change the value of `$nUpdateColumnsAllowed` to something higher than one. It's on [line 597](https://github.com/LOVDnl/LOVD3/blob/944934bfe70769809875535e46f5d6712a9ec86c/src/import.php#L597) right now.

I hope this helps!

**Comment by pengchy** [comment]
Hi Ivo,

1. Although the current notation is enough, it will be great  if you add some warning words as you wrote "Please note that this will permanently delete the data in this column. X values will be lost" when the user deactivate the columns.

2. Yes, more than one columns have been changed, so I want to update many columns. I think set the $nupdateColumnsAllowed variable to a larger number will resolve my problem.

Thank you!

**Comment by ifokkema** [comment]
Hi Pengcheng,

Did it work? If so, we can close this issue?


> 1. Although the current notation is enough, it will be great  if you add some warning words as you wrote "Please note that this will permanently delete the data in this column. X values will be lost" when the user deactivate the columns.

That warning is already there, I copied it from that page.

**Comment by pengchy** [comment]
Hi Ivo,
It is OK now.
This issue can be closed.
Best,
