### ISSUE TITLE
Add PubMed custom link to Remarks field in an Individual entry

### ISSUE THREAD

**Issue by leicray** [LOVDnl/LOVD3#525]
At present, the PubMed custom link is active in the Reference field of an entry for an Individual. It would be useful to have the PubMed custom link active in the Remarks field to allow inclusion of additional PubMed links.

**Comment by ifokkema** [comment]
Hi Raymond,
Do you mean for new LOVD3s? Or just for the GV shared? Because we can simply enable it for the GV shared, it doesn't require any change of code.

**Comment by leicray** [comment]
I mean just for the GV shared installation. In the past, I have included PubMed links in the Remarks field in my own installations of LOVD2.

**Comment by ifokkema** [comment]
OK, no problem! I've enabled this feature in the GV shared LOVD3!
