### ISSUE TITLE
Importing records fails on existing fields in database

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#53]
When importing a file into LOVD and updating existing records. LOVD gives errors for field values from the database.

To replicate this issue:

* Go to LOVD3 > Setup > Import data
* Select a text file with code below as content
* Select "Update existing data" as import mode
* Check "simulate"
* Click "import file"

~~~
### LOVD-version 3000-060 ### Full data download ### To import, do not remove or alter this header ###

## Variants_On_Genome ## Do not remove or alter this header ##
{{id}}	{{owned_by}}	{{VariantOnGenome/VIP}}
0000000297	00002	0
~~~

LOVD responds with an error:
> Error (Variants_On_Genome, line 5): Please fill in the 'VariantOnGenome/Genetic_origin' field.

Where the existing value for `VariantOnGenome/Genetic_origin` is null for that record.

**Comment by mkroon1** [comment]
Johan reiterated the need to fix this.

I think expected behavior would be that LOVD checks which fields are present in the import file and only fails to update records if there are errors concerning those fields.

**Comment by ifokkema** [comment]
Would it be a proper solution to loop the $_ERROR variable, check the field names, and remove any errors related to fields not in the file?
I'm linking this to our milestone, then.
