### ISSUE TITLE
How to submit or store CNV varitation

### ISSUE THREAD

**Issue by summerghw** [LOVDnl/LOVD3#536]

**Comment by ifokkema** [comment]
Hi, you can submit and store CNVs using HGVS. If the positions are uncertain, please see: http://varnomen.hgvs.org/recommendations/uncertain/

**Comment by summerghw** [comment]
thx

**Comment by summerghw** [comment]
Could i ask  another question "How to import other disase Database like the way import OMIM"

**Comment by ifokkema** [comment]
We have a tool for that, please see: https://github.com/LOVDnl/geneloader

**Comment by summerghw** [comment]
thx, i mean the geneloader scripts can only import OMIM database, if i want to import other disease database, should i use the same script and replace the morbidmap.txt context ?

**Comment by summerghw** [comment]
another question is , what if a large CNV located on several genes? will that var can only be a var on genome ?

**Comment by ifokkema** [comment]
> thx, i mean the geneloader scripts can only import OMIM database, if i want to import other disease database, should i use the same script and replace the morbidmap.txt content ?

You can do that, but simpler would be to use the LOVD3 import format (see the manual). If you make a download of a submission, you can see in which format a disease is stored. Remove the submission, add your diseases to this file, and import into your LOVD instance.

**Comment by ifokkema** [comment]
> another question is , what if a large CNV located on several genes? will that var can only be a var on genome ? If large CNV will be var on genome is that mean CNV can not link to disease, because only var on transcript can link to gene, and disease only link to gene.

You can map the variant to as many genes/transcripts as you like!

Note that a link to disease can also be made through adding an individual.

**Comment by summerghw** [comment]
@ifokkema , Thank you very much! now i understand. i had draw a rough draft about the  database model, 
![1628583529(1)](https://user-images.githubusercontent.com/39901746/128833074-0a4a8ecf-896b-4334-983f-90e43d401bc3.jpg)

In this model,  one var/ongenome can map to many var/ontranscript and many genes .
![image](https://user-images.githubusercontent.com/39901746/128833203-4fc7aa50-3402-4cd5-924c-f2f6995760b4.png)
 Am i right?

**Comment by ifokkema** [comment]
Perhaps this helps (it's almost 10 years old so details may be incorrect now, but the links are shown);

![3 0_datamodel_core_2012-05-21_aa_1000px](https://user-images.githubusercontent.com/11665018/128834649-e1cabb89-5b30-4d6d-944a-3bfd20cb32e0.jpg)

There is no direct link between `variants_on_genome` and `individuals`, but indeed there can be many "VOTs"; `variants_on_transcripts` connected to one "VOG" (`variants_on_genome`).

**Comment by summerghw** [comment]
thanks a lot. it was a great help.
