### ISSUE TITLE
Tooltip fails to display if quotes are present

### ISSUE THREAD

**Issue by martology** [LOVDnl/LOVD3#54]
In the prepareData function in objects.php, when processing the owned_by column, if there is a single quote in any of the columns used to construct the tooltip ($sInstitute, $sDepartment etc...) then the tooltip will not display correctly within Chrome. This has not been tested on other browsers.

To replicate the issue add a string with a single quote in it to the Department column for a user who owns a variant. Then find that variant in a viewlist and hover over the Owner name and the tooltip may not appear.

**Comment by mkroon1** [comment]
I would propose to solve this while migrating tooltips to [jQuery-UI](https://jqueryui.com/tooltip/) (which is already a dependency).

**Comment by ifokkema** [comment]
@mkroon1 It's actually just a matter of properly quoting the data before it's passed into the JS function, which will need to be done no matter the library... This doesn't mean we shouldn't make that move, but just fixing it now will be faster, we can look at migrating the tooltips later.
@martology Thanks for the submission! I'll quickly fix it directly in master, so it'll ship with the upcoming release!

**Comment by martology** [comment]
Great! Thanks for the prompt fix.
