### ISSUE TITLE
Add/enable new GB

### ISSUE THREAD

**Issue by loeswerkman** [LOVDnl/LOVD3#553]
- [x] Allow user to add new GB (`/genome_builds?add`)
  - [x] Give form to add new GB
     - [x]  Show list of all possible GBs (only show GBs of the currently active organism)
     - [x] Make sure only one new GB is added per form
  - [x] Add row in GB table
  - [x] Register custom DNA column
  - [x] Add columns in VOG table (start, end, DNA)
  - [x] Add columns in Transcripts table (start, end)

Related to #550

**Comment by loeswerkman** [comment]
Fix warning message:
![image](https://user-images.githubusercontent.com/46046247/134938087-d54d405f-8003-44fa-94a3-71cd54060d0f.png)

**Comment by ifokkema** [comment]
Please pull in some new commits; I made some fixes and changes.
a09500221d5454e8690cd0dcb9a5f3fcbe425070 - some fixes, standardization, and disabling of some code.
7ea8218e4fa59835b6fc220b27cf825d525fe01c - I noticed we have code in `inc-upgrade.php` that hasn't been activated yet. I activated it but got an error (this doesn't always happen). I now modified the code to always run, and updated the version.
357cf778df41e7246b5c8408aae5b6d969de8741 - Fixed the Notice and Warning that you have on your screenshot - it was my code that caused this.

Still to do:
- Modify the disabled code to add position fields to `TABLE_TRANSCRIPTS`, not `TABLE_VARIANTS_ON_TRANSCRIPTS`.
- Add check for users providing invalid genome builds.
- Make sure you try to recover from errors to create a situation that doesn't break the system hard.
