### ISSUE TITLE
Allow users to deactivate a genome build

### ISSUE THREAD

**Issue by loeswerkman** [LOVDnl/LOVD3#557]
- [x] Add button to the GB ViewEntry (VE) to deactivate the genome build (like done on other VEs)

- [x] Show form to deactive GB (`/genome_builds/hg19?remove`)
  - [x] Just give a warning and require a password, no other fields needed.

- [x] Give an error and block removal when:
   - [x] The chosen ID is not among the active IDs
   - [x] Password is incorrect
   - [x] There are variants on the chosen genome build that are not yet mapped on one of the other active genome builds

- [x] Delete entry if all variants are safely mapped on another genome build
   - [x] Delete row from Genome build table
   - [x] Alter VOG table (deleting the start, end, and DNA columns)
   - [x] Deactivate the custom DNA column
   - [x] Alter Transcripts table (deleting the start and end columns)

Related to #550

**Comment by ifokkema** [comment]
I've added some steps; it's better to deactivate the GB from its ViewEntry (VE). So the user must first look at the GB ViewList (VL), then click on one, see its details, then click "Options", then "Remove genome build", and then get the form.
The form itself can then just contain a warning (are you sure? blabla) and a password field.
When not all variants are also mapped on another genome build, block removal, not just a warning.
Deleting the entry is probably best done by first deleting the entry from the GB table. If done in any other order, the system will be broken for a short time (or a long time, if something goes wrong).

**Comment by ifokkema** [comment]
Closed by #558.
