### ISSUE TITLE
Implement VariantValidator for all genome builds in variant data entry form

### ISSUE THREAD

**Issue by loeswerkman** [LOVDnl/LOVD3#562]
- [x] Mark all DNA fields with their genome build (instead of only the first one)
- [x] Allow user to map from whichever DNA field that is in the form
  - [x] If the organism of choice is human:
    - [x] Make sure the HGVS check works on each field (apply ONLY regular expression on any gb that is not hg19 or hg38)
    - [x] Automatically fill all other DNA fields
  - [x] Fill in the `source`
- [x] In `inc-js-variants.php`, get rid of the usage of `$_GET['chromosome']` if you can (can we use the new data elements feature for this?)

**Comment by ifokkema** [comment]
@PeteCausey-Freeman
This will incorporate VV in the LOVD submission process. As mentioned before, my student @loeswerkman is working on supporting more than one genome build at a time in LOVD, this is one step in that process. We tried Docker today but didn't get far. I'll try again on Thursday in the office, if that doesn't work either, I'll send you the errors, maybe you can see what's up (so no need to do anything yet).

I know I am behind on my email a lot, I hope to be able to reply to all your emails today!

**Comment by PeteCausey-Freeman** [comment]
No problem. I'm very close to having a live dev API running.

Still worth trying with docker. 

Perhaps we can have a chat at some point @loeswerkman and work through the docker issues

**Comment by ifokkema** [comment]
Thanks! I'll let you know this Thursday how we did, with a bit of luck I can get it to run on my work PC :smile: :crossed_fingers:

**Comment by PeteCausey-Freeman** [comment]
Get a sensible computer ;)
