### ISSUE TITLE
Variants.php syntax error  ('search_VariantOnTranscript/DNA') 

### ISSUE THREAD

**Issue by angsm** [LOVDnl/LOVD3#579]
**Describe the bug**
All other pages of LOVD works **except** for /variants and its subpages. Pages resulted in error 500. /variants?create results in error 500 as well.

**To Reproduce**
1. Finish installation of LOVD set up page with everything with a green tick
2. Navigate to /variants

**Screenshots**
![image](https://user-images.githubusercontent.com/10956184/148006651-7fbc6aee-b002-423a-919c-53418ccd483f.png)

**Your software (please complete the following information):**
-  Apache/2.4.6 
- PHP 5.4.16 (cli) (built: Apr  1 2020 04:07:17)
- 5.5.68-MariaDB MariaDB Server
- Chrome / Firefox / Edge
- LOVD v.3.0 Build 27

**Additional information:**  
httpd.conf has been set to

<Directory "/var/www/html/src">  
     Options Indexes FollowSymLinks MultiViews  
     AllowOverride All  
     Order allow,deny  
     allow from all  
</Directory>

**Comment by angsm** [comment]
Error in apache

[Thu Jan 06 10:15:05.158126 2022] [:error] [pid 22637] [client 10.218.130.91:54599] PHP Parse error:  syntax error, unexpected 'list' (T_LIST) in /var/www/html/LOVDv.3.0/class/object_custom.php on line 619, referer: http://gis-dlap83v.gis.a-star.edu.sg/LOVDv.3.0/transcripts
[Thu Jan 06 10:15:09.453200 2022] [:error] [pid 22637] [client 10.218.130.91:54599] PHP Parse error:  syntax error, unexpected ''search_VariantOnTranscript/DN' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/LOVDv.3.0/variants.php on line 191, referer: http://gis-dlap83v.gis.a-star.edu.sg/LOVDv.3.0/individuals
[Thu Jan 06 10:15:12.493925 2022] [:error] [pid 23938] [client 10.218.130.91:50294] PHP Parse error:  syntax error, unexpected ''search_VariantOnTranscript/DN' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/LOVDv.3.0/variants.php on line 191
[Thu Jan 06 10:15:13.639929 2022] [:error] [pid 23939] [client 10.218.130.91:50295] PHP Parse error:  syntax error, unexpected ''search_VariantOnTranscript/DN' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/LOVDv.3.0/variants.php on line 191

**Comment by ifokkema** [comment]
Hi,
Thank you for your report. I can not reproduce this problem. Can you help me exclude a few possibilities?
- Did you download LOVD from the LOVD website or are you using the master branch from git?
- Are you sure no modifications have been made to the code? Can you somehow verify this, using a diff tool for instance?
- Your PHP version reports being a CLI version, which is not the PHP version that Apache will use. Can you verify the PHP version as used by Apache?
Thank you!

**Comment by ifokkema** [comment]
Closing to inactivity. If this is still an issue for you, please let me know.
