### ISSUE TITLE
LOVD uses wrong protocol to open LRG web pages

### ISSUE THREAD

**Issue by leicray** [LOVDnl/LOVD3#599]
**Describe the bug**
LOVD gene homepages provide a link to the LRG entry for those genes for which an LRG has been created. The link ought to open the relevant LRG page but does not do so correctly

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://lovd.nl/COL1A1
2. Click on the "Genomic reference" link to access LRG_1
3. This causes the user's browser to attempt to fetch the destination resource using the ftp protocol

**Expected behavior**
The link that LOVD displays for access to the LRG_1 page should begin with "https://" rather than "ftp://"

**Comment by ifokkema** [comment]
Good point, thanks. Not sure why it's set to FTP. I'll have a look at it!
