### ISSUE TITLE
Batch addition of genes

### ISSUE THREAD

**Issue by rahulraj7007** [LOVDnl/LOVD3#60]
Hi,

I have started playing with LOVD and it is indeed a highly useful software.

 I am trying to implement LOVD to see if it can be a form of variant database in our lab. I am coming across an issue of adding genes. We have over 6000 genes that we are planning to incorporate into database. Is there any option to  import as a batch the genes(As adding  individual genes into the database is eating up lot of time) or do you have any LOVD import file which contains most of the clinically relevant genes that could be used for this purpose?

**Comment by ifokkema** [comment]
Hi,
I'm glad to hear you like LOVD!
Yes, I understand, and many have had this issue (we ourselves, too). That is why we developed [the geneloader](https://github.com/LOVDnl/geneloader). It normally will create all genes into LOVD that are supported, but if you create a text file with the 6000 gene symbols that you would like to have created, and save it into the directory where you have downloaded the gene loader, you can tell the gene loader to just create those genes.

The gene loader is an interactive script. Just download and run it, and it will ask you questions so you won't need to remember any command line arguments. If you're having any issues with it, feel free to post your question on the gene loader GitHub page!

**Comment by rahulraj7007** [comment]
Fantastic..!! Thank you very much..
