### ISSUE TITLE
Turn off xdebug on travis

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#64]
Travis seems to have xdebug enabled, since composer is complaining about it with the message:
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

I don't think it's a major performance drag for our tests, but with the frequent timeouts on travis, it may be worthwhile to turn debugging off.

**Comment by ifokkema** [comment]
Hmmm.... I wonder why it's enabled by default! But I agree, we don't use it, so it's worth a shot!

**Comment by mkroon1** [comment]
From the [travis docs](https://docs.travis-ci.com/user/languages/php):

> To disable xdebug, add this to your configuration:
>
> ```
before_script:
 - phpenv config-rm xdebug.ini
```
