### ISSUE TITLE
Restrict length of owned_by selection field

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#65]
When the "owned_by" selection field gets too long because of long user's names, the form layout is distorted by the browser. This does not look very good.
Somehow make sure that the field has a maximum width, solving this problem.

**Comment by mkroon1** [comment]
Fixed in c5f627c, though I noticed other input elements sometimes also overflow the table cells (not as distorting), so we may decide to give them a max length too.
