### ISSUE TITLE
GeneTests should be GTR

### ISSUE THREAD

**Issue by amalheiro** [LOVDnl/LOVD3#657]
**Describe the bug**
1. On your gene pages, in the 'Links to other resources' section, there is a row 'GeneTests'. The name should be GTR or NIH Genetic Testing Registry.
The links correctly go to GTR.
2. The update may also be needed in your submission template

**To Reproduce**
1. Go to 'https://databases.lovd.nl/shared/genes/TNFRSF10A'
2. Scroll down to 'Links to other resources'
![image](https://github.com/user-attachments/assets/1c3662c6-d5be-4789-ba46-6e6e8542bf72)

**Expected behavior**
The link label should be "GTR" or "NIH Genetic Testing Registry"

If you have questions or need anything from the GTR team, please let us know: gtr@ncbi.nlm.nih.gov
Thank you,
Adriana Malheiro, MS, LCGC
Director, NIH Genetic Testing Registry (GTR)
adriana.malheiro@nih.gov

**Comment by ifokkema** [comment]
Thanks for your report, @amalheiro! I have renamed the resource in the LOVD software and updated the live system.

**Comment by amalheiro** [comment]
Thank you, looks great!
