### ISSUE TITLE
Import: Panel_size of individual in panelid field not checked properly

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#67]
When importing multiple individuals where the `panelid` field of one of them refers to an individual in the file, LOVD does not properly check the `panel_size` field of the individual referred to.
File example:
```
### LOVD-version 3000-150 ### Full data download ### To import, do not remove or alter this header ###
## Individuals ## Do not remove or alter this header ##
{{id}}	{{panelid}}	{{panel_size}}
1		4
2		1
3	1	1
```
Returns error message:
```
Error (Individuals, line 6): Panel ID "1" refers to an individual, not a panel (group of individuals). If you want to configure that individual as a panel, set its 'Panel size' field to a value higher than 1.
```
Which is not correct.

**Comment by mkroon1** [comment]
I can not reproduce the error with the given import file in an empty database. 

The error does occur when an existing individual with id=1 is present in the database with panel_size=1. When in *update mode* I think it should ignore in this case the database individual when there's a new individual defined in the import file. I will fix that.
