### ISSUE TITLE
Adapt for new Mutalyzer namechecker API

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#73]
LOVD stores identifiers for alternative transcript variants ([see mutalyzer docs](https://humgenprojects.lumc.nl/trac/mutalyzer/wiki/VariantDescriptions/GeneSymbol)). However, these are unstable and LOVD may end up with unpredictable results when it uses the Mutalyzer API.

An upcoming change in [mutalyzer](https://github.com/mutalyzer/mutalyzer) makes it possible to define references to transcripts using an RNA accession number (e.g. *NG_009105.1(NM_020061):g.=*).

The Mutalyzer API calls in LOVD will have to be adapted to make use of this change.

**Comment by ifokkema** [comment]
Shall we rename this issue and rewrite it to solving this problem on the side of LOVD? Or perhaps better: create a new issue, and drop this one off the milestone?

**Comment by mkroon1** [comment]
Closing in favour of #76
