### ISSUE TITLE
Unstable identifiers for transcript variants

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#76]
LOVD stores identifiers for alternative transcript variants ([see mutalyzer docs](https://humgenprojects.lumc.nl/trac/mutalyzer/wiki/VariantDescriptions/GeneSymbol)). However, these are unstable and LOVD may end up with unpredictable results when it uses the Mutalyzer API.

We can reload identifiers using the [getTranscriptsAndInfo](https://mutalyzer.nl/soap-api#op.getTranscriptsAndInfo) API call. To lower the number of extra API calls, we can perhaps reload an identifier when it is being used, and only if it hasn't been reloaded a certain amount of time.

**Comment by ifokkema** [comment]
It would be good to implement this as part of the `lovd_getRNAProteinPrediction()` function. We just need to find a way for it to "see" that the v-number might be expired.
