### ISSUE TITLE
Download link missing on gene homepage

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#78]
Higher-level users can check _"allow public to download variant entries"_ on a gene entry edit page. However, on the gene's "homepage", there is no download link to be found when not logged in.

For an example on the shared DB, see: [ZNF143](http://databases.lovd.nl/shared/genes/ZNF143)

**Comment by ifokkema** [comment]
Absolutely correct. It's more than a missing link however, it requires some coding as well. From the LOVD 2Do file (translated and/or corrected if needed):
- How does the public make downloads?
  * Security! Remove all non-public entries and non-public columns!
  * Link from the gene homepage?
  * Link from the viewList, after applying search terms, just like in LOVD2?
    - But then, how to make sure that the search terms are parsed and taken into account? Make that code into a function?
  * Download setting is per gene (LOVD2-style), but what about the intergenic variants?

We'll need to set up this issue with a task list, and we might need to split these points into separate tasks as well.

**Comment by ifokkema** [comment]
> Most of export functionality already exists in `download.php`. On the gene homepage we can link to `/download/all/gene/NAME`, and modify `download.php` to check if the download flag for the gene is set and filter non-public columns and records if needed.

It would indeed by logical to use the same URL. For the VL downloads, we can open a separate issue if we want to work on that soon, too.

`download.php` needs to check authorization, and proceed how you said only if user is not authorized and setting is enabled. The check for authorization can be done [here](https://github.com/LOVDnl/LOVD3/blob/master/src/download.php#L87), but we may need a different filter than just `gene`. Sadly, the code currently can process only one filter per URL. Make the filter `gene_public` or so? The `gene` filter is defined [here](https://github.com/LOVDnl/LOVD3/blob/master/src/download.php#L254), and needs to be modified to filter variants, individuals and phenotype data for status. Filtering the columns will need to be done somewhere [here](https://github.com/LOVDnl/LOVD3/blob/master/src/download.php#L489).

**Comment by mkroon1** [comment]
Not to forget: there was a request to allow downloading data for all public genes in one go (J). Consdider to implement that as part of this issue or create a new issue.

**Comment by ifokkema** [comment]
> Not to forget: there was a request to allow downloading data for all public genes in one go (J). Consdider to implement that as part of this issue or create a new issue.

Hmm... what would that be for? I guess it would make more sense as a separate issue. We'll run into major memory issues if we'd do that the same way... :disappointed:

**Comment by mkroon1** [comment]
Created new issue for downloading all public data at once: #184
