### ISSUE TITLE
[Website] Mention <genesymbol>.lovd.nl more prominent on lovd.nl homepage

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#79]
Most visitors of lovd.nl are interested in the content of the databases for specific genes. The current homepage mentions GENESYMBOL.lovd.nl as an option, but this is in a relatively small message box (the rest of the homepage is largely concerned with the LOVD software package).

For those users, it would be an improvement if this message was more prominent, and for example if one could immediatly type in their gene of interest and go directly to the list of DBs that store variants for that gene.

_(Request from Johan)_

**Comment by ifokkema** [comment]
Do you, or him, have any specific ideas of what that should look like? Should we put the LOVD3 site source code also in Git?

**Comment by ifokkema** [comment]
Implemented just now.
