### ISSUE TITLE
Minor improvements to import.php regarding the `variants_found` column

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#82]
- [ ] When `variants_found` contains a value other than 0 or 1, the error message stating this is given twice.
- [ ] We can simply accept any numeric value over 1 as 1, since the column is a boolean rather than a counter but users often think it counts.

**Comment by mkroon1** [comment]
Importing test file for `variants_found` issue: [variants_found.txt](https://github.com/LOVDnl/LOVD3/files/776946/variants_found.txt), will result in the following messages:

```
The field 'Have variants been found?' must contain either a '0' or a '1'.
Error (Screenings, line 38): The field 'variants_found' must contain either a '0' or a '1'.
The field 'Have variants been found?' must contain either a '0' or a '1'.
Error (Screenings, line 39): The field 'variants_found' must contain either a '0' or a '1'.
Error (Screenings, line 39): The 'variants_found' field is limited to numbers no higher than 9.
```

Line 39 in the test file generates three messages, where the bottom message is confusing as it's less general than the others.
