### ISSUE TITLE
Tex files are executable

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#88]
Two tex files in the doc source ([Create_a_gene_variant_database.tex](https://github.com/LOVDnl/LOVD3/blob/master/doc/tex/Create_a_gene_variant_database.tex) and [config.txt](https://github.com/LOVDnl/LOVD3/blob/master/doc/tex/config.tex)) are executable.

@ifokkema can you tell me if this is on purpose?

**Comment by ifokkema** [comment]
Hi! Not on purpose, executable bit can be removed :)
