### ISSUE TITLE
Include script to convert the LOVD2 download format to the LOVD3 format

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#96]
LOVD3 still lacks an importer for LOVD2 data. While this is a pretty complicated task, we can relatively easily start with a conversion tool that takes an LOVD2 file and convert it to LOVD3 format. It will not take care of transferring user accounts, it will not take care of mapping custom columns, but at least it will make moving data a lot easier. It may be (loosely) based on the `get_variant_info.php` script developed by @ifokkema that is fetching information needed for LOVD3 using limited (sort of LOVD2 style) data and fetches transcript IDs etc.
- [x] This script will handle one gene per conversion only.
- [x] The gene must exist in the LOVD3 installation already.
- [x] Before conversion is done, the transcript should be chosen. This transcript should already exist in LOVD3.
- [x] The script should take the LOVD2 format, and create the full LOVD3 format.
- [x] Information missing in the LOVD2 file that LOVD3 needs should be provided by this script (`get_variant_info.php` should take care of all of that, I think).

**Comment by mkroon1** [comment]
@ifokkema, where can I find `get_variant_info.php`?

**Comment by mkroon1** [comment]
As discussed today: custom columns will be ignored during conversion.

**Comment by mkroon1** [comment]
> As discussed today: custom columns will be ignored during conversion.

Change of plans: custom columns will be appended to LOVD3 import file. They should be ignored during import if they don't exist in the LOVD3 installation.
