### ISSUE TITLE
Configurable homepage

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#98]
Currently LOVD redirects the user to `genes.php` when visiting the base URL of the LOVD installation. This is a request to make the default web page configurable (requested by J).

Proposal: let administrator or manager set a custom URL to be the homepage. `genes.php` would be the value after installation. A relative path would be considered relative to LOVD's `ROOT_URL`. An absolute URL with protocol and hostname is used as given.

**Comment by ifokkema** [comment]
Absolute URLs will not be a good idea. If people want a different start page they can just upload a file to LOVD (that redirects if necessary). It can merely be *very* harmful in case a manager leaves their PC logged into LOVD and people tinker with the settings. Paths can also not contain `../` or similar. LOVD should carefully check the page that this setting is being set to. I would actually argue it's safer to provide a list of options. If people sometimes really want their own welcoming pages, then they could also just edit the index.php...? How many requests have we received about this?

**Comment by mkroon1** [comment]
> How many requests have we received about this?

Just the one.

**Comment by mkroon1** [comment]
Just decided: we fix the most important use case where there is only one gene in the database. In that case, submitters/curators and visitors (not logged in) will be redirected to `genes/SYMBOL` from the homepage.

We won't make anything general for selecting arbitrary pages as the default home page.
